"""
Ground-truth item set for the undertone-coherence floor probe.

This file IS the artifact's center of gravity. Each item is YOUR judgment about
whether a neutral combination sits below the coherence floor, and WHY. The model
gets tested against this, never the reverse.

Label values (binary):
  "clean"           - the neutrals cohere; reads as a deliberate, resolved palette
  "undertone_clash" - warm-family and cool-family neutrals presented as a match;
                      they fight on the temperature axis (the FLOOR violation)

reasoning: ONE sentence, in your own words, naming the specific temperature
           conflict (or, for clean items, why it resolves). This is what proves
           the trained eye. For an undertone_clash, you should be able to point
           at the warm piece and the cool piece. Do not hand-wave it.

source:   "real"       - real product/editorial photo (watch image rights if public)
          "controlled" - mocked/constructed swatch where you control exact colors

SCOPE NOTE: This set contains ONLY clean and undertone_clash. muddy_midtone,
value_no_anchor, and patterns are deliberately excluded and discussed in
WRITEUP.md as reasoned scope decisions. Do not add them here.

LABELING RULE (hard rule, do not bend):
Only label an item `undertone_clash` if you can NAME the warm piece and the cool
piece, that is, state the temperature direction of the conflict in words. If you
see "something off" but cannot point at which piece is warm and which is cool,
DO NOT label it undertone_clash and DO NOT include it. That item has drifted
into the muddy territory we deliberately cut, and including it would reintroduce
the "trust my taste" attack surface this whole artifact is built to avoid.
Naming the warm piece and the cool piece IS your defense line in an interview.
"""

ITEMS = [
    # --- CONTROLLED swatch anchors (generated by make_swatches.py) -----------
    # These are flat color blocks, not garments. They calibrate the probe with
    # exact b* values. They are the EASY case for a model. Real garment photos
    # (source="real") must carry the rest of the set. b*_note records the
    # measured temperature so each label is backed by numbers, not assertion.
    {
        "id": "sw_clean_warm",
        "image": "images/sw_clean_warm.jpg",
        "label": "clean",
        "reasoning": "Cream, camel and tobacco are all warm-family neutrals stepped light to dark, so the palette resolves as one choice.",
        "source": "controlled",
        "b_note": "all warm: b* +15.8 / +34.6 / +24.2",
    },
    {
        "id": "sw_clean_cool",
        "image": "images/sw_clean_cool.jpg",
        "label": "clean",
        "reasoning": "Oyster, dove grey and charcoal are all cool-based with a clear value range, so the tonal stack resolves.",
        "source": "controlled",
        "b_note": "all cool/neutral: b* -2.1 / -4.5 / -2.5",
    },
    {
        "id": "sw_clash_camel_bluegrey",
        "image": "images/sw_clash_camel_bluegrey.jpg",
        "label": "undertone_clash",
        "reasoning": "A warm camel sits against a cool blue-grey as if matched, so the two neutrals fight on the warm-cool axis.",
        "source": "controlled",
        "b_note": "WIDE gap, math catches it: warm +33.7 vs cool -7.3",
    },
    {
        "id": "sw_clash_warmbeige_cooltaupe",
        "image": "images/sw_clash_warmbeige_cooltaupe.jpg",
        "label": "undertone_clash",
        "reasoning": "A yellow-based warm beige is paired with a grey-based cool taupe at similar lightness, a near-match that diverges on undertone.",
        "source": "controlled",
        "b_note": "SUBTLE gap, cool side (-2.8) inside ambiguous band; eye sees clash, math stays quiet",
    },
    {
        "id": "sw_clash_cream_oyster",
        "image": "images/sw_clash_cream_oyster.jpg",
        "label": "undertone_clash",
        "reasoning": "Two off-whites that look matched but split on temperature, warm cream against cool oyster, so the pairing reads slightly wrong.",
        "source": "controlled",
        "b_note": "SUBTLE gap, cool side (-2.2) inside ambiguous band; eye sees clash, math stays quiet",
    },

    # --- REAL garment items: YOU add ~20-25 below, named item_001.jpg etc. ---
    # Source evenly-lit photos. For each undertone_clash, name the warm piece and
    # the cool piece in reasoning. Leave b_note off real items or fill after you
    # run colorlib on them.
    {
        "id": "gray_top_brown_pant",
        "image": "images/outfit_clash_1.png",
        "label": "undertone_clash",
        "reasoning": "A brown (warm) trouser is clasing with a gray (cool) top.",
        "source": "real",
        "b_note": "cool side b*=-0.2, barely in ambiguous",
    },
    {
        "id": "gray_monochrome_outfit",
        "image": "images/outfit_clean_1.png",
        "label": "clean",
        "reasoning": "The trouser, sweater, and bag are complementary shades of gray, offering a clean monochromatic look.",
        "source": "real",
        "b_note": "all one family (ambiguous/cool); resolves — b* -8.1 / -1.7 / -5.6 / -1.3",
    },
    {
        "id": "brown_monochrome_outfit",
        "image": "images/outfit_clean_2.png",
        "label": "clean",
        "reasoning": "The trouser, sweater, and bag are complementary shades of brown, offering a clean monochromatic look.",
        "source": "real",
        "b_note": "all one family (ambiguous/warm); resolves — b* +5.4 / +5.3 / +2.1 / +13.8",
    },
    {
        "id": "black_white_pant_outfit",
        "image": "images/outfit_clean_3.png",
        "label": "clean",
        "reasoning": "The trouser, top, and bag are crisp, clean shades of black and white that pair well with one another.",
        "source": "real",
        "b_note": "all one family (ambiguous/warm); resolves — b* +13.4 / +1.5 / +4.2 / -3.0",
    },
    {
        "id": "brown_top_gray_pant_outfit",
        "image": "images/outfit_clash_2.png",
        "label": "undertone_clash",
        "reasoning": "The brown sweater clashes with the light gray pants.",
        "source": "real",
        "b_note": "warm b*=6.6 vs cool b*=-4.6",
    },
    {
        "id": "brown_jacket_gray_top_pants_outfit",
        "image": "images/outfit_clash_3.png",
        "label": "undertone_clash",
        "reasoning": "The brown jacket clashes with the cool tone, monochromatic look underneath",
        "source": "real",
        "b_note": "all pixels land in ambiguous band (b* -0.1 / -3.3 / -0.5 / +4.2 at w=0.06); math finds no split, eye-only call — consider excluding",
    },
]

LABELS = ("clean", "undertone_clash")
